spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_manager?useSSL=false
    username: root
    password: xinghun1314

mybatis:
  configuration:
    map-underscore-to-camel-case: true

